sonar.organization=lobziik
sonar.projectKey=lobziik_tuturu

sonar.sources=app/src
sonar.tests=app/src
sonar.test.inclusions=**/*.test.ts

sonar.javascript.lcov.reportPaths=app/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/public/**,**/dist/**
