#!/bin/bash
# Container entrypoint - write environment to file before starting systemd
set -euo pipefail

ENV_FILE="/etc/tuturu/env"

# Create env directory
mkdir -p /etc/tuturu

# Write environment variables to file for systemd services
{
    echo "# Generated by entrypoint.sh"
    [[ -n "${DOMAIN:-}" ]] && echo "DOMAIN=${DOMAIN}"
    [[ -n "${LETSENCRYPT_EMAIL:-}" ]] && echo "LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}"
    [[ -n "${EXTERNAL_IP:-}" ]] && echo "EXTERNAL_IP=${EXTERNAL_IP}"
    [[ -n "${TURN_USERNAME:-}" ]] && echo "TURN_USERNAME=${TURN_USERNAME}"
    [[ -n "${TURN_PASSWORD:-}" ]] && echo "TURN_PASSWORD=${TURN_PASSWORD}"
    [[ -n "${TURN_MIN_PORT:-}" ]] && echo "TURN_MIN_PORT=${TURN_MIN_PORT}"
    [[ -n "${TURN_MAX_PORT:-}" ]] && echo "TURN_MAX_PORT=${TURN_MAX_PORT}"
    [[ -n "${LETSENCRYPT_STAGING:-}" ]] && echo "LETSENCRYPT_STAGING=${LETSENCRYPT_STAGING}"
} > "${ENV_FILE}"

chmod 600 "${ENV_FILE}"

# Start systemd
exec /sbin/init
