#!/bin/bash
# Container entrypoint - write environment to file before starting systemd
set -euo pipefail

log() { echo "[entrypoint] $*"; }

log "Starting tuturu container entrypoint"

ENV_FILE="/etc/tuturu/env"
log "Environment file: ${ENV_FILE}"

# Create env directory
log "Creating /etc/tuturu directory"
mkdir -p /etc/tuturu

# Write environment variables to file for systemd services
log "Writing environment variables to ${ENV_FILE}"
{
    echo "# Generated by entrypoint.sh"
    [[ -n "${DOMAIN:-}" ]] && echo "DOMAIN=${DOMAIN}"
    [[ -n "${LETSENCRYPT_EMAIL:-}" ]] && echo "LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}"
    [[ -n "${EXTERNAL_IP:-}" ]] && echo "EXTERNAL_IP=${EXTERNAL_IP}"
    [[ -n "${TURN_USERNAME:-}" ]] && echo "TURN_USERNAME=${TURN_USERNAME}"
    [[ -n "${TURN_PASSWORD:-}" ]] && echo "TURN_PASSWORD=${TURN_PASSWORD}"
    [[ -n "${TURN_MIN_PORT:-}" ]] && echo "TURN_MIN_PORT=${TURN_MIN_PORT}"
    [[ -n "${TURN_MAX_PORT:-}" ]] && echo "TURN_MAX_PORT=${TURN_MAX_PORT}"
    [[ -n "${LETSENCRYPT_STAGING:-}" ]] && echo "LETSENCRYPT_STAGING=${LETSENCRYPT_STAGING}"
} > "${ENV_FILE}"

log "Environment variables written:"
[[ -n "${DOMAIN:-}" ]] && log "  DOMAIN=${DOMAIN}"
[[ -n "${LETSENCRYPT_EMAIL:-}" ]] && log "  LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}"
[[ -n "${EXTERNAL_IP:-}" ]] && log "  EXTERNAL_IP=${EXTERNAL_IP}"
[[ -n "${TURN_USERNAME:-}" ]] && log "  TURN_USERNAME=${TURN_USERNAME}"
[[ -n "${TURN_PASSWORD:-}" ]] && log "  TURN_PASSWORD=[set, ${#TURN_PASSWORD} chars]"
[[ -n "${TURN_MIN_PORT:-}" ]] && log "  TURN_MIN_PORT=${TURN_MIN_PORT}"
[[ -n "${TURN_MAX_PORT:-}" ]] && log "  TURN_MAX_PORT=${TURN_MAX_PORT}"
[[ -n "${LETSENCRYPT_STAGING:-}" ]] && log "  LETSENCRYPT_STAGING=${LETSENCRYPT_STAGING}"

log "Setting permissions on ${ENV_FILE}"
chmod 600 "${ENV_FILE}"

# Start systemd
log "Starting systemd (exec /sbin/init)"
exec /sbin/init
