#!/bin/bash
# tuturu-init.sh
# Initialize tuturu configuration from environment variables
# FAIL FAST: Exit immediately on any error or missing required variable

set -euo pipefail

log() { echo "[tuturu-init] $*"; }
error() { echo "[tuturu-init] ERROR: $*" >&2; exit 1; }

# =============================================================================
# Load environment file if it exists
# =============================================================================
if [[ -f /etc/tuturu/env ]]; then
    log "Loading environment from /etc/tuturu/env"
    set -a
    source /etc/tuturu/env
    set +a
fi

# =============================================================================
# Validate required environment variables - FAIL FAST
# =============================================================================
log "Validating required environment variables..."

if [[ -z "${DOMAIN:-}" ]]; then
    error "DOMAIN is required. Set it to your base domain (e.g., call.example.com)"
fi

if [[ -z "${LETSENCRYPT_EMAIL:-}" ]]; then
    error "LETSENCRYPT_EMAIL is required. Set it to an email for Let's Encrypt notifications"
fi

if [[ -z "${EXTERNAL_IP:-}" ]]; then
    error "EXTERNAL_IP is required. Set it to the public IP of this server"
fi

# Validate EXTERNAL_IP is a valid IPv4 address
if ! [[ "${EXTERNAL_IP}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
    error "EXTERNAL_IP must be a valid IPv4 address. Got: ${EXTERNAL_IP}"
fi

export INTERNAL_IP=$(ip route get 1 | awk '{print $7; exit}')


# =============================================================================
# Set defaults for optional variables
# =============================================================================
export TURN_USERNAME="${TURN_USERNAME:-webrtc}"
export TURN_MIN_PORT="${TURN_MIN_PORT:-49152}"
export TURN_MAX_PORT="${TURN_MAX_PORT:-49200}"
export STUN_SERVERS="${STUN_SERVERS:-stun:t.${DOMAIN}:3478}"

# Generate TURN password if not provided
if [[ -z "${TURN_PASSWORD:-}" ]]; then
    log "Generating TURN password..."
    TURN_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=')
    export TURN_PASSWORD
fi

# =============================================================================
# Log configuration (without sensitive data)
# =============================================================================
log "Configuration:"
log "  DOMAIN: ${DOMAIN}"
log "  LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}"
log "  EXTERNAL_IP: ${EXTERNAL_IP}"
log "  INTERNAL_IP: ${INTERNAL_IP}"
log "  TURN_USERNAME: ${TURN_USERNAME}"
log "  TURN_PORT_RANGE: ${TURN_MIN_PORT}-${TURN_MAX_PORT}"
log "  TURN_PASSWORD: [set, ${#TURN_PASSWORD} chars]"
log "  STUN_SERVERS: ${STUN_SERVERS}"

# =============================================================================
# Generate nginx configuration
# =============================================================================
log "Generating nginx configuration..."

if [[ ! -f /etc/nginx/nginx.conf.template ]]; then
    error "nginx.conf.template not found at /etc/nginx/nginx.conf.template"
fi

envsubst '${DOMAIN}' \
    < /etc/nginx/nginx.conf.template \
    > /etc/nginx/nginx.conf

log "nginx configuration written to /etc/nginx/nginx.conf"

# =============================================================================
# Generate coturn configuration
# =============================================================================
log "Generating coturn configuration..."

if [[ ! -f /etc/coturn/turnserver.conf.template ]]; then
    error "turnserver.conf.template not found at /etc/coturn/turnserver.conf.template"
fi

envsubst '${DOMAIN} ${EXTERNAL_IP} ${INTERNAL_IP} ${TURN_USERNAME} ${TURN_PASSWORD} ${TURN_MIN_PORT} ${TURN_MAX_PORT}' \
    < /etc/coturn/turnserver.conf.template \
    > /etc/coturn/turnserver.conf

# Secure coturn config (contains password)
chmod 600 /etc/coturn/turnserver.conf

log "coturn configuration written to /etc/coturn/turnserver.conf"

# =============================================================================
# Save environment for other services
# =============================================================================
log "Saving environment to /etc/tuturu/env..."

cat > /etc/tuturu/env << EOF
# Generated by tuturu-init.sh
DOMAIN=${DOMAIN}
LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
EXTERNAL_IP=${EXTERNAL_IP}
INTERNAL_IP=${INTERNAL_IP}
TURN_USERNAME=${TURN_USERNAME}
TURN_PASSWORD=${TURN_PASSWORD}
TURN_MIN_PORT=${TURN_MIN_PORT}
TURN_MAX_PORT=${TURN_MAX_PORT}
STUN_SERVERS=${STUN_SERVERS}
FORCE_RELAY=${FORCE_RELAY:-false}
EOF

chmod 600 /etc/tuturu/env

# =============================================================================
# Create required directories
# =============================================================================
log "Creating required directories..."

mkdir -p /var/www/acme/.well-known/acme-challenge
mkdir -p /var/lib/tuturu

log "Initialization complete"
